# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
       npm
    path: $(npm_config_cache)
  displayName: Cache npm
- script: npm i
  displayName: 'i'
- script: npm install -g @angular/cli
  displayName: 'install the cli globally'
- script: npx webdriver-manager update --versions.chrome=80.0.3987.106
  displayName: 'update webdriver-manager'
- script: npm run build:express
  displayName: 'build the app'
- script: npm run ci:run:win
  displayName: 'run protractor'
