# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
- pwsh: |
  $theurl = "http://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise64.msi"
  mkdir c:\tmp
  $output = "c:\tmp\chrome.msi"
  Invoke-WebRequest -Uri $theurl -OutFile $output -ErrorAction SilentlyContinue
  msiexec /q /i c:\tmp\chrome.msi
  start-sleep -Seconds 300 # sleep for 5 mins just to allow updates to be processed 
  Remove-Item -Path c:\tmp\chrome.msi –Force
- pwsh: |
   echo "##vso[task.prependpath]$env:CHROMEWEBDRIVER"
  displayName: Adds ChromeWebDriver for Selenium to PATH 
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
       npm
    path: $(npm_config_cache)
  displayName: Cache npm
- script: npm i
  displayName: 'i'
- script: npm install -g @angular/cli
  displayName: 'install the cli globally'
- script: npx webdriver-manager update
  displayName: 'update webdriver-manager'
- script: npm run build:express
  displayName: 'build the app'
- script: npm run ci:run:win
  displayName: 'run protractor'